<?xml version="1.0" encoding="gb2312"?>
<!DOCTYPE message[
<!ELEMENT message ANY>
<!ELEMENT author (name)>
<!ATTLIST name a_ID ID  #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT book (book_name)>
<!ATTLIST book author IDREFS  #REQUIRED>
<!ELEMENT book_name (#PCDATA)>
]>
<message>
<author>
<name a_ID="a1">
xiaoli
</name>
</author>
<author>
<name a_ID="a2">
xiaowang
</name>
</author>
<book author="a1 a2">
<book_name>
abc
</book_name>
</book>
</message>
