<?xml version="1.0" encoding="gb2312"?>
<!DOCTYPE message[
<!ELEMENT message ANY>
<!ELEMENT persion (name,sex,age?,lxfs)>
<!ELEMENT lxfs (#PCDATA|tel|email)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT email (#PCDATA)>
]>
<message>
<persion>
<name>xiaowang</name>
<sex>male</sex>
<lxfs>
<tel>1234567</tel>
</lxfs>
</persion>
<persion>
<name>xiaoli</name>
<sex>male</sex>
<age>23</age>
<lxfs>
只能通过邮件联系。
<email>xiaoli@163.com</email>
</lxfs>
</persion>
</message>