<?xml  version="1.0"?>
<!DOCTYPE message [
<!ELEMENT message ANY>
<!ELEMENT book (b:name,price)>
<!ELEMENT author (a:name, sex)>
<!ELEMENT b:name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT a:name (first,last)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ATTLIST b:name xmlns:b CDATA #REQUIRED>
<!ATTLIST a:name xmlns:a CDATA #REQUIRED>
]>
<message>
<book>
<b:name xmlns:b="beijing">
abc
</b:name>
<author>
<a:name xmlns:a="jilin">
<first>li</first>
<last>lin</last>
</a:name>
<sex>male</sex>
</author>
<price>
55
</price>
</book>
</message>
